package config

import "os"

var (
	POSTGRE_HOST     = "POSTGRE_HOST"
	POSTGRE_PORT     = "POSTGRE_PORT"
	POSTGRE_DB_NAME  = "POSTGRE_DB_NAME"
	POSTGRE_USERNAME = "POSTGRE_USERNAME"
	POSTGRE_PASSWORD = "POSTGRE_PASSWORD"

	SECRET_KEY = "SECRET_KEY"
)

func InitConfig() {
	POSTGRE_HOST = os.Getenv("POSTGRE_HOST")
	POSTGRE_PORT = os.Getenv("POSTGRE_PORT")
	POSTGRE_DB_NAME = os.Getenv("POSTGRE_DB_NAME")
	POSTGRE_USERNAME = os.Getenv("POSTGRE_USERNAME")
	POSTGRE_PASSWORD = os.Getenv("POSTGRE_PASSWORD")

	SECRET_KEY = os.Getenv("SECRET_KEY")
}
